src/App.js, src/assets/datas/menuDatas.json, src/components/convenience/Register.jsx, src/styles/page/register.scss
=> [Add] register api 연결

package-lock.json, package.json, src/App.js, src/components/product/ProductItem.jsx, src/components/product/ProductNav.jsx, src/pages/ProductList.jsx, src/store/apis/base.js, src/store/apis/product.js, src/store/utils/function.js, src/styles/page/product.scss
=> [Add] 상품페이지 분기 처리

src/components/ui/HeaderMenu.jsx, src/components/ui/HeaderToggle.jsx, src/styles/layout/header.scss
=> [Add] 메뉴 구조 수정

src/App.js, src/components/convenience/Login.jsx, src/components/convenience/Mypage.jsx, src/components/convenience/Register.jsx, src/components/convenience/UpdateMyPage.jsx, src/styles/page/convenience/login.scss, src/styles/page/convenience/myPage.scss, src/styles/page/convenience/register.scss
=> [Add] 마이페이지 구현

src/components/convenience/ChangePw.jsx, src/components/convenience/Login.jsx, src/components/convenience/Mypage.jsx, src/components/convenience/Register.jsx, src/components/convenience/UpdateMyPage.jsx, src/styles/index.scss, src/styles/page/convenience/changePw.scss, src/styles/page/convenience/updateMyPage.scss
=> [Add] 마이페이지 수정, 비밀번호 변경 수정 구현

src/App.js, src/components/employees/AddEmployeeModal.jsx, src/components/employees/Attendance.jsx, src/components/employees/EmployeeInfo.jsx, src/components/employees/LeaveWork.jsx, src/components/employees/ModifyEmployeeModal.jsx, src/components/employees/TerminateEmployeeModal.jsx, src/pages/Employees.jsx, src/pages/Inventory.jsx, src/pages/Paymentlist.jsx, src/styles/index.scss, src/styles/page/employees/AddEmployeeModal.scss, src/styles/page/employees/employees.scss, src/styles/page/employees/employeesinfo.scss, src/styles/page/employees/terminateemployeemodal.scss, src/styles/page/inventory/inventory.scss, src/styles/page/payment/payment.scss, src/styles/page/payment/paymentlist.scss
=> [Add] 결제 내역 조회

src/pages/Paymentlist.jsx, src/styles/page/employees/employees.scss, src/styles/page/inventory/inventory.scss, src/styles/page/payment/paymentlist.scss
=> [Fix] 결제 내역 css 전체 수정보완

src/components/home/HomeItemEdit.jsx, src/components/home/HomeModal.jsx, src/pages/Home.jsx, src/styles/Modal.scss, src/styles/page/home/home.scss, src/styles/page/home/homeModal.scss
=> [Fix] main page modal

src/App.js, src/components/convenience/FindPw.jsx, src/components/convenience/Login.jsx, src/styles/index.scss, src/styles/page/convenience/findPw.scss
=> [Add] 비밀번호 찾기 구현

src/components/convenience/FindId.jsx, src/components/convenience/FindIdInfo.jsx, src/components/convenience/Login.jsx, src/components/convenience/Mypage.jsx, src/styles/index.scss, src/styles/page/convenience/findIdInfo.scss
=> [Add] 아이디 찾기 구현

src/App.js, src/components/convenience/FindPw.jsx, src/components/convenience/Login.jsx, src/components/convenience/Logout.jsx, src/components/convenience/Register.jsx, src/components/ui/HeaderMenu.jsx
- #49 
- HeaderMenu에 Logout component 연결
- App.js 파일에 Logout.jsx파일 route 연결
- Logout api 연결
- Logout 기능 구현
- Logout api 백이랑 통신 테스트 필요
=> [Add] 로그아웃 구현

package-lock.json, package.json, src/App.js, src/assets/datas/menuDatas.json, src/components/paymentlist/ReceiptModal.jsx, src/components/paymentlist/RefundConfirmModal.jsx, src/components/paymentlist/RefundModal.jsx, src/pages/Payment.jsx, src/pages/Paymentlist.jsx, src/pages/Paymenttest.jsx, src/styles/base/_common.scss, src/styles/index.scss, src/styles/page/employees/AddEmployeeModal.scss, src/styles/page/payment/payment.scss, src/styles/page/paymentlist/paymentlist.scss, src/styles/page/paymentlist/refund.scss
- #50 
- 결제 기능과 관련된 UI 및 로직을 구현
- 결제 종류(카드, 현금, 기타)에 따라서 다른 모달을 띄워줌
=> [Fix] 결제 내역 페이지 재구조화

src/App.js, src/components/home/HomeItem.jsx, src/components/home/HomeItemEdit.jsx, src/components/home/HomeModal.jsx, src/components/home/HomeModalList.jsx, src/pages/Home.jsx, src/styles/Modal.scss, src/styles/base/_common.scss, src/styles/page/home/home.scss
- close #59 
- API 통신 테스트
- success
- 링크 연결
- 백에서 받아온 seq랑 프론트에서 가지고 있는 id 값 대조해서 일치하면 링크 텍스트 return
```const handleLink = (seq) => {
for (let i = 0; i < menuDatas.length; i++) {
if(seq === menuDatas[i].id) {
return menuDatas[i].link;
}
}
}
- 구조 수정
- 메인페이지 메뉴 수정시 나오는 모달에서 좌측리스트와 우측리스트 하나의 컴포넌트로 사용하게 수정
- 모달 배경 잠금 처리
- 다같이 쓰는 모달 컴포넌트 배경 잠기게 수정
=> [Add] 메인페이지 즐겨찾기 메뉴 구현

src/assets/datas/orderListDatas.json, src/components/order/OrderListItem.jsx, src/pages/Order.jsx
- close #63 
- 컴포넌트화 + map
- OrderListItem 컴포넌트 생성 
- 발주 상태 callStatus에 따른 분기 처리
- 접수완료, 배송중, 배송 완료로 나눔
- API 테스트 필요
- 발주 대기(장바구니) 상태는 하나의 페이지로 분리 예정
=> [Add] 발주 내역 페이지 컴포넌트 및 분기 처리

.dockerignore, .github/workflows/cicd.yml, dockerfile
- #68 
- dockerfile 파일 설정
- build 까지 완료
- .dockerignore 설정
- git action을 위한 cicd.yml 설정
- 메인 브랜치에 push되면 이미지를 빌드하고 도커 허브에 푸시하도록 함
- SSH Remote Commands 부분 아직 미구현
- organization에 DOCKERHUB_USERNAME, DOCKERHUB_TOKEN 추가
=> [Add] docker 설정

src/App.js, src/components/customer/RegisterCustomer.jsx, src/styles/page/customer/customerRegister.scss
- #61 
- 간편 가입 UI(input, button, numpad) 수정
- numpad 기능 수정
- 간편 가입 API 연결, 테스트
- 백엔드 코드 수정중
=> [Add] 간편 가입 구현

src/components/CheckMark.jsx, src/components/payment/Cashpay.jsx, src/components/payment/CashpayReceipt.jsx, src/pages/Payment.jsx, src/styles/Modal.scss, src/styles/checkmark.scss, src/styles/page/payment/cashpay.scss, src/styles/page/payment/cashpayreceipt.scss
- #79 
- 현금 결제 내역에 결제된 상품 목록을 추가해서 전송하게 함
- 이제 상품을 어떻게 받아올 건지 받아온 상품을 어떻게 잘 넣어줄 건지 구상해야 함
=> [Add] 결제 내역 데이터에 상품 목록 추가

src/components/payment/Cardpay.jsx, src/pages/Payment.jsx, src/styles/page/payment/cardpay.scss
- #80 
- 기존의 카드 결제 모달창을 띄우는 방법에서,
카드 결제 컴포넌트를 함수 컴포넌트로 변경하여 카드 결제 버튼을 눌렀을 때, 바로 결제가 진행되도록 수정함
- 결제가 완료된 후 사용자에게 페이지 처리를 어떻게 해줘야 할지 고민해봐야 함
=> [Add] 카드 결제 api 연결

src/App.js, src/components/analysis/AddCost.jsx, src/styles/index.scss, src/styles/page/analysis/addCost.scss
- #76 
- addcost component 연결
- addcost css import 연결
- addcost 페이지 전체 UI, css 
- keypad 함수 적용
- 금액 입력 1000 이상 되면 ',' 추가되는 기능 구현 예정
- addcost 페이지 API 연결
=> [Add] 분석 페이지 addcost 페이지 구현

.github/workflows/cicd.yml
=> ci: make deploy to ec2

.github/workflows/cicd.yml
=> ci: make dispatch trigger

.github/workflows/cicd.yml
ssh 접근 방식을 password가 아니라 key방식으로 변경해요.
=> fix: fix broken ssh action

.github/workflows/cicd.yml
=> fix: fix broken ssh action -2

src/assets/datas/paymentllistDatas.json, src/components/payment/Cashpay.jsx, src/components/payment/Point.jsx, src/pages/Payment.jsx, src/styles/index.scss, src/styles/page/payment/cashpay.scss, src/styles/page/payment/point.scss
=> [Add] 포인트 모달창 ui

.github/workflows/cicd.yml
- close #94 
- organizatiosn secrets 수정으로 인한 cicd 코드 수정
- USERNAME으로 다 변경
=> [Fix] cicd secrets 수정

src/components/analysis/AddCost.jsx
- #86 
- addCost 페이지 title 수정 (금액 입력 -> 비용 입력)
- addComma 함수 사용 (천 단위 숫자 입력되면 자동으로 콤마로 구분함)
=> [Add] 분석 페이지 addCost 구현

src/App.js, src/components/analysis/Analysis.jsx, src/styles/index.scss, src/styles/page/analysis/analysis.scss
- #97 
- 분석 페이지
- 메인 페이지 UI 구현
- 각 페이지 별로 링크 연결
=> [Add] 분석 메인 페이지 구현

src/App.js, src/assets/datas/menuDatas.json, src/components/order/OrderCartAddModal.jsx, src/components/order/OrderCartNav.jsx, src/components/order/OrderDetailNav.jsx, src/components/order/OrderList.jsx, src/components/stock/StockListItemMain.jsx, src/components/ui/HeaderMenu.jsx, src/pages/Order.jsx, src/pages/OrderCart.jsx, src/pages/OrderDetail.jsx, src/store/apis/product.js, src/styles/Modal.scss, src/styles/index.scss, src/styles/page/order/orderCartAddModal.scss, src/styles/page/order/orderDetail.scss, src/styles/page/order/orderList.scss
- close #99 
- 발주 바구니 페이지 + 발주 내역 페이지 + 발주 내역 상세 페이지
- 발주 내역 페이지 및 발주 바구니 페이지 구현
- 발주 아이템 컴포넌트 공유
- 컴포넌트 공유에 따른 구조 수정
- 발주 내역 페이지 페이지네이션 추가
- API 연결 필요
- 발주 바구니 페이지 체크박스 구현 필요
=> [Add] 발주 관련 페이지 구현 

src/assets/datas/menuDatas.json, src/components/analysis/Analysis.jsx, src/styles/page/analysis/analysis.scss
- #97 
- 분석 페이지
- 월세 및 관리비 링크 수정
- 분석 페이지 css 수정
- menuDatas link 연결
=> [Add] 분석 페이지 

src/App.js, src/components/analysis/Cost.jsx, src/styles/index.scss, src/styles/page/analysis/cost.scss
- #102 
- 월세 및 관리비 페이지
- cost 페이지 UI 구현
- addCost페이지, updateCost 페이지 링크 연결
=> [Add] 월세 및 관리비 페이지

src/App.js, src/pages/Delivery.jsx, src/styles/index.scss, src/styles/page/delivery/delivery.scss
- close #105 
- 배달 목록 페이지 UI
- 상품 목록 3개까지만 보이고 그 이상은 상세페이지에서 보이도록 하기
- 배달 sort UI
- 대기, 접수, 완료 3가지 상태로 분류
- 배달 상단 sort 기능 추가 예정
=> [Add] 배달 목록 페이지 구현

package-lock.json, package.json, src/App.js, src/components/analysis/Calendar.jsx, src/components/analysis/DailySales.jsx, src/components/analysis/MonthlySales.jsx, src/components/analysis/SalesReport.jsx, src/components/analysis/WeeklySales.jsx, src/styles/index.scss, src/styles/page/analysis/salesReport.scss
- #104 
- 매출 보고서
- 일별, 주별, 월별 매출 보고서 컴포넌트 생성, route, 링크 연결
- 매출 보고서 UI 구현
- 일별, 주별, 월별 매출 nav 디자인 수정
- 캘린더 기능 구현해서 조회할 수 있도록 구현 예정
=> [Add] 매출 보고서 페이지

src/App.js, src/components/order/OrderCartAddModal.jsx, src/components/order/OrderCartNav.jsx, src/components/order/OrderDetailNav.jsx, src/components/order/OrderItem.jsx, src/components/order/OrderList.jsx, src/components/order/OrderListItem.jsx, src/components/ui/HeaderMenu.jsx, src/pages/Order.jsx, src/pages/OrderCart.jsx, src/pages/OrderDetail.jsx, src/styles/layout/header.scss
- close #112 
- 발주 장바구니, 발주 내역, 발주 내역 상세 API 코드 작성
- 컴포넌트 구조 변경
- 상세 페이지 컴포넌트화
- API 통신 테스트 필요
- 메뉴에 임시 로그인, 회원가입 버튼 추가 (AWS)
=> [Add] 발주 관련 페이지 API 연결 및 컴포넌트 구조

src/components/payment/Cashpay.jsx, src/components/payment/TosspayReceipt.jsx, src/pages/Employees.jsx, src/pages/Payment.jsx, src/store/utils/tosspay.js, src/styles/page/payment/payment.scss
- #116 
- 토스페이 API를 연결
- 임의로 넣어줬던 결제 정보, 결제 상품들을 없애고 바코드 스캔으로 받은 상품들이 넘겨지도록 수정
- 결제가 완료를 알리는 모달창에 결제 내역의 간단한 정보들을 추가
- 결제가 완료되면 결제된 상품들이 화면상에서 초기화 되도록 기능을 추가해야함
=> [Add] 토스페이 API

src/styles/page/analysis/analysis.scss, src/styles/page/analysis/cost.scss
- #119 
- 분석 페이지
- 분석 메인 페이지 메뉴 테두리 점선 -> 실선으로 수정
- 월세 및 관리비 페이지 메뉴 테두리 점선 -> 실선으로 수정 
- 분석 메인 페이지
- 월세 및 관리비 페이지
=> [Fix] 분석 페이지 css 수정

src/components/delivery/DeliveryDetail.jsx, src/components/delivery/DeliveryList.jsx, src/styles/page/delivery/delivery.scss, src/styles/page/delivery/deliveryDetail.scss
- close #113 
- 배달 상세페이지 UI 구현
- 자잘한 CSS 수정
- 상세페이지 상품들 map 돌릴 예정
=> [Fix] 배달 페이지 UI 수정

src/components/order/OrderCartAddModal.jsx, src/components/order/OrderCartNav.jsx, src/pages/Order.jsx, src/pages/OrderCart.jsx, src/store/apis/base.js, src/styles/page/order/orderCartAddModal.scss
- close #122 
- API 연결 주소를 AWS로 수정
- baseURL 수정
- 상품 추가 모달 CSS 수정
- 검색어 해당 상품 없을시 분기 처리
=> [Fix] 배달 페이지 API 및 CSS 수정

src/components/employees/AddEmployeeModal.jsx, src/components/employees/Attendance.jsx, src/components/employees/EmployeeInfo.jsx, src/components/employees/LeaveWork.jsx, src/components/employees/TerminateEmployeeModal.jsx, src/components/inventory/InvenModal.jsx, src/components/payment/Cashpay.jsx, src/pages/Employees.jsx, src/pages/Inventory.jsx, src/pages/Payment.jsx, src/pages/Paymentlist.jsx, src/styles/page/payment/payment.scss
- #124 
- 결제 상품 목록 분기처리
- useRef 코드 수정
=> [Fix] apiURL 세팅, 결제 페이지

src/components/payment/TosspayReceipt.jsx, src/components/payment/TosspayReceiptInfoModal.jsx, src/pages/Inventory.jsx, src/pages/Payment.jsx, src/store/utils/tosspay.js, src/styles/page/employees/employees.scss, src/styles/page/inventory/inventory.scss
- #128 
- 시재 페이지의 전체적인 css를 수정 보완
-
=> [Fix] 시재 페이지 분기처리, css 보완

src/components/analysis/AddCost.jsx, src/components/convenience/Login.jsx
- #131 
- addcost 저장하기 버튼 함수 구현
- addcost API 연결 및 주소 수정 
- API 테스트 필요
=> [Add] addcost 페이지 구현

src/components/home/HomeModal.jsx, src/components/order/OrderCartAddModal.jsx, src/components/order/OrderCartNav.jsx, src/components/order/OrderDetailNav.jsx, src/components/order/OrderItem.jsx, src/components/order/OrderList.jsx, src/components/order/OrderListItem.jsx, src/pages/Home.jsx, src/pages/Order.jsx, src/pages/OrderCart.jsx, src/pages/OrderDetail.jsx, src/styles/page/order/orderList.scss
- close #129 
- API 통신 테스트 완료
- 발주 대기 페이지 상품 삭제 체크박스 상태 관리
- 전부 체크시, 몇개만 체크시 모두 구현 완료
- handleAllCheck 전부 체크 관리 함수
- handleCheck 개별 체크 관리 함수
- 발주 상품 추가 하면 목록 리렌더링
- isDone state 만들어서 dependency
- 총 상품 종류 수 추가
- 발주 대기 목록 상품 없을시 API 분기 처리 추후 삭제 예정
=> [Add] 발주 페이지 API 통신 테스트 및 대기 상품 삭제

src/pages/ProductList.jsx, src/styles/page/product.scss
- close #130 
- 검색시 API 전송 텀 두기
- debounce 처리
- 0.3초
```
const timer = setTimeout(() => {
getProductList(keyword)
.then((response) => {
console.log(response.data);
console.log(response.data.ProductList);
setProduct(response.data);
})
.catch((error) => {
console.error(error);
})
}, 300); 
return () => clearTimeout(timer);
- 상품 목록 없을 때 분기 처리
- 무한스크롤 구현 실패 다시 도전 예정
- 쓰로틀링과 디바운싱
- https://www.zerocho.com/category/JavaScript/post/59a8e9cb15ac0000182794fa
=> [Fix] 상품페이지 검색 기능 최적화

src/components/convenience/Mypage.jsx, src/components/convenience/Register.jsx, src/components/convenience/UpdateMyPage.jsx, src/styles/page/convenience/myPage.scss, src/styles/page/convenience/updateMyPage.scss
- #141 
- API 주소 수정
- css pointer-events: none; 추가 -> readOnly 처럼 입력 이벤트 비활성화됨
- 정보 수정 데이터 입력할 때 오류가 뜨는 현상 수정
- API 테스트 필요
=> [Add] 마이페이지 수정

src/App.js, src/components/analysis/UpdateCost.jsx
- #143 
- 월세 및 관리비 수정 페이지 UI 구현
- API 주소 연결
- API 테스트 필요
=> [Add] 월세 및 관리비 수정 페이지 구현

src/components/order/OrderCartNav.jsx, src/components/order/OrderDetailNav.jsx
- #145 
- 접수 완료 상태일 때 발주 취소 API 연결 완료
- 발주 상태에 따른 버튼 UI 분기 처리
- 접수완료 : 발주 취소 가능
- 배송중, 배송완료 : 발주 취소 불가능
=> [Add] 발주 취소 API 연결

src/components/analysis/DailySales.jsx, src/components/analysis/MonthlySales.jsx, src/components/analysis/MyChart.js, src/components/analysis/YearSales.jsx, src/styles/index.scss, src/styles/page/analysis/sales.scss
- #147
- MyChart.js 상단의 label 명을 " " 빈문자열로 변경, 주석 정리
- API 주소 수정, res 응답 받아 오는 부분 수정
- 조회하기를 눌렀을 때 Chart 부분에 데이터 넣는 기능 구현
- dailySales.scss -> sales.scss으로 변경 (일별/월별/연별 공통으로 쓰기 위해서)
- API 테스트 필요
- 차트 디자인 수정 필요
=> [Add] 일별 매출 보고서 구현

src/App.js, src/components/analysis/ImcomeReport.jsx, src/styles/index.scss, src/styles/page/analysis/imcomeReport.scss
- #149 
- 손익 보고서 페이지 UI 구현
- 손익 보고서 페이지 css import
- 손익 보고서 페이지 route 연결
=> [Add] 손익 보고서 페이지 UI 구현

.dockerignore, .github/workflows/cicd.yml, .gitignore, public/index.html, src/components/delivery/DeliveryMap.jsx, src/pages/Delivery.jsx, src/styles/base/_common.scss, src/styles/page/delivery/delivery.scss
- #152 
- 배달 점포로 등록되지 않은 경우 등록할 수 있도록 분기 처리
- 카카오 지도 API 사용
- 마커로 위치 표시
- 주소, 위도, 경도 값
- 추후 주소 검색 추가 예정
- cicd에 카카오 지도 key 값 추가
- 카카오 지도 검색 기능이 안 좋아서 주소 검색 후 지도에 마크 표시 예정
=> [Add] 배달 점포 등록 및 카카오 지도 API

src/components/analysis/AddCost.jsx, src/styles/page/analysis/addCost.scss
- #102  
- 비용을 입력할 연도, 날짜 캘린더 추가
- nav 부분 추가해서 title과 calendar 부분 css 수정
- content background color, input, button css 수정
- costYear, costMonth 임시로 설정한 날짜 -> calendar로 날짜 선택해서 설정할 수 있도록 구현
=> [Add] 월세 및 관리비 입력 페이지 구현

src/components/analysis/AddCost.jsx, src/components/analysis/UpdateCost.jsx, src/styles/index.scss, src/styles/page/analysis/updateCost.scss
- #143 
- 캘린더, 조회 버튼 추가
- 클래스명 수정
- css 연결
- API 테스트 필요
=> [Add] 월세 및 관리비 수정페이지 구현

src/components/payment/Cashpay.jsx, src/components/payment/CashpayReceipt.jsx, src/components/payment/TosspayReceipt.jsx, src/components/payment/TosspayReceiptInfoModal.jsx, src/pages/Payment.jsx, src/store/utils/tosspay.js
- #136 
- 결제 완료 후 상품 목록을 초기화하면서 받은 금액, 거스름 돈까지 초기화 되는 문제를 수정
- tosspay 결제 영수증을 연결
- tosspayreceiptModal에서 어떤 버튼을 눌렀을 때, payment의 상품 목록들을 초기화시킬지 생각해봐야 함
=> [Fix] 결제 영수증 연결

src/components/analysis/AddCost.jsx
- #102 
- 비용 금액 parseInt 작업
- 콤마 제거 작업
- API 연결 테스트 성공
- DB에 데이터 전달 완료 
- 화면
- DB
=> [Fix] 월세 및 관리비 입력 페이지 수정

src/components/inventory/InvenModal.jsx, src/pages/Inventory.jsx, src/styles/page/inventory/inventory.scss
- #162 
- 시재의 번호를 {item.seq}가 아닌 프론트에서 최신 시재부터 1부터 부여함
- 특이사항 메모의 분기처리
=> [Fix] 시재 페이지 수정

package-lock.json, package.json, src/components/delivery/DeliveryMap.jsx, src/pages/Delivery.jsx, src/styles/index.scss, src/styles/page/delivery/deliveryMap.scss
- close #152 
- 카카오 지도 API 사용
- 카카오 지도 API에 있는 리스트 띄우기 예제 HTML 코드라 사용이 어려워서 라이브러리 사용
- 다음 우편번호 API --> react-daum-postcode
- 주소 검색 후 해당하는 주소 선택시 오른쪽 지도에 마커로 표시
- 주소, 위도, 경도 값
- CSS 수정 필요
=> [Add] 카카오 지도 API + 다음 우편번호 API

src/components/analysis/UpdateCost.jsx
- #143 
- 조회 버튼 API 연결
- 원하는 날짜의 월세 및 관리비 데이터 불러오기 성공
- 조회버튼 클릭 -> 해당 날짜의 데이터 나옴
- 불러온 데이터 콤마 적용
- 수정 API 테스트 필요
=> [Add] 월세 관리비 수정 페이지

src/components/order/OrderCartAddModal.jsx, src/components/order/OrderCartNav.jsx, src/components/order/OrderDetailNav.jsx, src/components/order/OrderList.jsx, src/components/order/OrderListItem.jsx, src/pages/Order.jsx, src/pages/OrderCart.jsx, src/pages/OrderDetail.jsx, src/store/apis/base.js, src/styles/page/order/orderList.scss
- close #170 
- 원가 변수 수정
- priceOrigin
- API 헤더 토큰 추가
- API 통신시 서버에 이제 무조건 토큰 보내야함
- 발주 페이지 최적화
- React.memo 사용
- amount가 바뀐 항목만 리렌더링
```
export default React.memo(OrderListItem, areEqual);
function areEqual(prev, next) {
return (
prev.amount === next.amount && prev.selectedItems === next.selectedItems
);
}
```
- API 수정 필요
=> [Fix] 발주 페이지 API 수정 및 최적화

src/components/payment/Cashpay.jsx, src/components/paymentlist/RefundConfirmModal.jsx, src/components/paymentlist/RefundModal.jsx, src/pages/Employees.jsx, src/pages/Payment.jsx, src/pages/Paymentlist.jsx, src/store/utils/tosspay.js, src/styles/page/paymentlist/paymentlist.scss
- #168
- paymentOneList API 연결해 결제 상세 내역을 확인
- paymentlist API 연결해 전체 결제 내역을 조회
- cancelpayment API 연결해 환불 기능 추가
- 카드번호 검색 api 요청 필요
- response에 receipt-url 추가 요청 필요
=> [Add] 분기처리. 환불 API 추가

src/components/paymentlist/ReceiptModal.jsx, src/components/paymentlist/RefundConfirmModal.jsx, src/pages/Paymentlist.jsx
- #168 
- 환불 영수증에 response의 receiptURL을 연결
- 이미 결제 취소된 내역에 대해서 중복 취소를 방지
- 
- 현금 결제는 영수증을 어떻게 해야할 지 논의가 필요함
=> [Fix] 환불 영수증을 연결

src/App.js, src/components/analysis/ImcomeReport.jsx, src/components/analysis/MonthlyImcome.jsx, src/components/analysis/YearImcome.jsx, src/styles/index.scss, src/styles/page/analysis/imcome.scss, src/styles/page/analysis/imcomeReport.scss
- #179 
- 손익보고서 페이지
- imcomeReport css 수정
- imcome css 연결 (월별/연별 css로 통일)
- 월별 / 연별로 조회할 수 있도록 나눔 (route 연결하고 app.js 수정)
- 캘린더 기능 추가
- 캘린더 조회 API 테스트 완료
=> [Add] 손익보고서 구현

src/components/delivery/DeliveryButton.jsx, src/components/delivery/DeliveryDetail.jsx, src/components/delivery/DeliveryList.jsx, src/pages/Delivery.jsx, src/store/utils/function.js, src/styles/page/delivery/delivery.scss, src/styles/page/delivery/deliveryDetail.scss
- #183 
- 배달 상태 업데이트
- 각 상태당 다음 단계로 넘어가는 기능 구현
- 배달 취소 기능 구현
- 주문 접수 대기 상태일 때만 취소 가능
- 배달 상태에 따른 분기 처리
- 4가지의 배달 상태에 따라서 각각 버튼 UI 다르게 뜨도록 함
- 배달 상태 개수 API 논의 필요
=> [Fix] 배달 상태 업데이트 및 분기 처리

src/components/analysis/DailySales.jsx, src/components/analysis/MonthlyImcome.jsx, src/components/analysis/MonthlySales.jsx, src/components/analysis/YearImcome.jsx, src/components/analysis/YearSales.jsx, src/store/apis/MyChart.js, src/styles/page/analysis/sales.scss
- #187 
- 필요없는 코드 정리
- API 주소 ${baseURL}로 수정
- 데이터가 있을 때 값 설정, 없을 때는 0으로 설정해서 보여주기
- 일별, 월별, 연별로 최대값 따로 설정이 필요해서 설정
(현재 데이터가 많이 없어서 최대값을 높게 설정하면 안보이기 때문에)
- 차트 별로 label 이름 따로 설정
- 차트 데이터 설정해서 bar 나오게 설정
- 데이터가 있는 경우
- 데이터가 없는 경우
- 차트 디자인 수정 필요
=> [Add] 매출보고서 구현

package-lock.json, package.json, src/components/home/HomeModal.jsx, src/components/ui/HeaderAlarm.jsx, src/components/ui/HeaderMenu.jsx, src/pages/Home.jsx, src/styles/index.scss, src/styles/layout/header.scss, src/styles/layout/headerAlarm.scss, src/styles/layout/headerMenu.scss
- close #193 
- 알림 기능 구현
- 제일 처음에 받고, 지정한 시간 간격으로 알림 받음
- 유통기한 지난 상품 + 유통기한 임박한 상품 리스트 
- 알림 UXUI
- 알림을 안 읽으면 빨간 점 떠있는 상태
- 읽으면 사라짐
- 추후 알림 간격 조정 (현재 1분 간격)
- 개발이라 알림 두번 뜸
=> [Add] 알림 기능 구현

src/components/analysis/AddCost.jsx, src/components/analysis/Cost.jsx, src/components/analysis/DailySales.jsx, src/components/analysis/ImcomeReport.jsx, src/components/analysis/MonthlyImcome.jsx, src/components/analysis/MonthlySales.jsx, src/components/analysis/SalesReport.jsx, src/components/analysis/UpdateCost.jsx, src/components/analysis/YearImcome.jsx, src/components/analysis/YearSales.jsx, src/pages/Analysis.jsx, src/styles/page/analysis/analysis.scss, src/styles/page/analysis/cost.scss, src/styles/page/analysis/imcome.scss, src/styles/page/analysis/imcomeReport.scss, src/styles/page/analysis/sales.scss, src/styles/page/analysis/salesReport.scss
- #191 
- 전반적인 코드 정리
- analysis, cost 페이지 div 전체적인 부분에서 버튼 선택 되도록 수정
- 버튼 디자인 변경
- 매출보고서, 손익보고서 처음 들어갈 때 데이터가 없을 때 빈 화면 -> 날짜 선택을 안내하는 화면이 나오도록 구현
- analysis 페이지 css 수정
- 매출, 손익보고서 빈화면
=> [add] 분석페이지 UX/UI 수정

src/components/delivery/DeliveryDetail.jsx, src/components/delivery/DeliveryList.jsx, src/components/ui/HeaderMenu.jsx, src/pages/Delivery.jsx, src/pages/Login.jsx, src/styles/page/delivery/delivery.scss, src/styles/page/delivery/deliveryDetail.scss
- close #188 
- 상세 페이지 내에서도 배송 상태 업데이트
- active sort 바뀔 때
- 페이지 번호 리셋
- 상태별 현재 개수 띄워주기 완료
- 상단에 현재 편의점 주소 추가
- 배달 상세페이지 단가, 수량, 금액 현재 안 맞아서 백에서 수정 예정
=> [Fix] 배달 상세 페이지 버튼 기능 및 페이지 오류

src/App.js, src/components/PrivateRoutes.jsx, src/components/convenience/ChangePw.jsx, src/components/convenience/FindId.jsx, src/components/convenience/FindPw.jsx, src/components/convenience/FindPwInfo.jsx, src/components/customer/RegisterCustomer.jsx, src/components/order/OrderListItem.jsx, src/components/stock/StockAddModal.jsx, src/components/ui/HeaderMenu.jsx, src/pages/Login.jsx, src/store/apis/base.js, src/store/utils/function.js
- #208 
- PrivateRoutes를 이용한 로그인 유무 분기 처리
- API URI 주소 수정
- headers 빠져있는 거 수정
- 토큰 처리 필요
=> [Add] private routes

src/App.js, src/components/analysis/MonthlyImcome.jsx, src/components/analysis/YearImcome.jsx, src/components/delivery/DeliveryDetail.jsx, src/components/delivery/DeliveryList.jsx, src/components/delivery/DeliveryMap.jsx, src/components/employees/Attendance.jsx, src/components/employees/LeaveWork.jsx, src/components/order/OrderCartAddModal.jsx, src/components/order/OrderCartNav.jsx, src/components/order/OrderDetailNav.jsx, src/components/order/OrderListItem.jsx, src/components/paymentlist/RefundConfirmModal.jsx, src/components/paymentlist/RefundModal.jsx, src/components/stock/StockAddModal.jsx, src/components/ui/HeaderMenu.jsx, src/pages/Delivery.jsx, src/pages/Order.jsx, src/pages/OrderCart.jsx, src/pages/OrderDetail.jsx, src/pages/ProductList.jsx, src/pages/Stock.jsx, src/store/apis/base.js, src/store/utils/easypay.js, src/store/utils/function.js
- close #212 
- 토큰 변수 일괄 수정
- 페이지마다 불러서 사용
=> [Fix] access token 변수 일괄 수정

src/components/order/OrderCartAddModal.jsx, src/components/stock/StockAddModal.jsx, src/components/stock/StockList.jsx, src/components/stock/StockListItemMain.jsx, src/pages/Stock.jsx
- close #216 
- 재고 관리 페이지 상품 발주 추가 에러 수정
- API 바뀐 거 적용시킴
- 자잘한 토스트 메시지도 수정
=> [Fix] 재고 관리 API 수정

dockerfile, nginx.conf
이슈 연결이 필요하다면 이슈 생성해서 수정해주세용 ㅋㅋ
페이지 새로고침을 하거나, url로 세부 페이지 접근시에 접근이 안되던 문제를 해결해요.
- nginx config를 수정했어요.
- 빌드할 때 nginx config도 함께 포함하도록 해요.
- 
-
=> feat: 페이지 새로고침시 접근 안되는 문제 해결

src/pages/Register.jsx
- #211 
- API 주소 수정
- 주석 정리
- 아이디 유효성 검사
- 대소문자 구분
- 숫자 입력
- 유효성 검사 완료 후 아이디를 바꿨을 때
- 비밀번호 유효성 검사
- 특수 문자 사용 : ~ ! @ # $ % ^ & * . ?  
- 회원 가입 자격 안되었을 때 가입 버튼 클릭 시 토스트 띄워주기
- 회원 가입 자격 안되었을 때 가입 버튼 클릭 시
- 대소문자 구분
- 유효성 검사 통과 후 아이디 수정했을 때
=> [Add] 회원 가입 페이지 수정

src/pages/Login.jsx, src/styles/page/convenience/login.scss
- #220 
- 주석 정리
- API 수정
- 로그인 css 수정
- 아이디 찾기, 비밀번호 찾기, 회원 가입 간격 늘리기
- 아이디 저장 체크박스 수정
=> [Add] 로그인 페이지 수정

package-lock.json, package.json, src/App.js, src/components/PosRoutes.jsx, src/components/PrivateRoutes.jsx, src/components/layout/Header.jsx, src/components/ui/HeaderAlarm.jsx, src/components/ui/HeaderToggle.jsx, src/pages/HomeKiosk.jsx, src/pages/Login.jsx, src/store/atom/posState.js, src/styles/index.scss, src/styles/layout/header.scss, src/styles/layout/headerToggleModal.scss, src/styles/page/home/homeKiosk.scss
- close #198 
- close #208 
- 전체적인 분기 처리
- 로그인 유무 분기 처리
- POS / KIOSK 분기 처리
- route 구조 수정
- PrivateRoutes : 로그인 확인
- PosRoutes : 포스 상태인지 확인
- POS + KIOSK 상태 recoil로 관리
- POS / KIOSK 전환시 관리자 번호 입력하도록 구현
- 관리자 임시 번호 현재 1234
=> [Add] 로그인 및 포스+키오스크 분기 처리

src/components/layout/Header.jsx, src/styles/index.scss, src/styles/layout/headerKiosk.scss
- close #224 
- 키오스크 헤더 홈 버튼 
- 키오스크 헤더 결제하기 및 상품 둘러보기 버튼
- 결제하기 페이지일 때는 상품 둘러보기 버튼
- 상품 페이지일 때는 결제하기 버튼
=> [Add] 키오스크 모드 메뉴 구현

src/components/employees/ModifyEmployeeModal.jsx, src/components/payment/Cashpay.jsx, src/components/payment/CashpayReceipt.jsx, src/components/paymentlist/ReceiptModal.jsx, src/pages/EmployeeInfo.jsx, src/pages/Payment.jsx, src/styles/page/employees/terminateemployeemodal.scss, src/styles/page/payment/cashpay.scss, src/styles/page/payment/payment.scss
- #226 
- 직원 정보를 수정할 때 원래의 정보를 띄움
- 직원 퇴사 ui 수정
- 받은 금액과 거스름 돈을 바로바로 반영해, 받음 금액이 초기화되면 전부 초기화, 받은 금액이 더 적으면 결제로 넘어가지 않음
- 결제 페이지의 현금 결제에 현금 영수증을 연결
- 결제 페이지 ui 수정 - 불필요한 버튼들을 제거
=> [Fix] 테스팅 후 버그를 수정해요

src/styles/page/convenience/login.scss
=> [Fix] Login css 수정

src/components/convenience/ChangePw.jsx, src/components/convenience/UpdateMyPage.jsx, src/pages/Mypage.jsx, src/styles/index.scss, src/styles/page/convenience/myPage.scss, src/styles/page/convenience/updateMyPage.scss
- #222 
- 마이 페이지
- 마이 페이지와 수정 페이지 구분할 수 있도록 css 수정
- 마이 페이지, 수정 페이지 page-title 추가
- 비밀번호 변경
- 빈 값으로 비밀번호 변경 시 toast.error 띄워줌
- 현재 비밀번호 다르게 입력하면 toast.error 띄워줌
- 현재 비밀번호와 새 비밀번호를 똑같이 입력하면 toast.error 띄워줌
- 새 비밀번호와 확인 비밀번호 다르게 입력하면 toast.error 띄워줌
=> [Add] 마이 페이지 수정

src/components/analysis/AddCost.jsx, src/components/analysis/UpdateCost.jsx, src/styles/page/analysis/addCost.scss, src/styles/page/analysis/updateCost.scss
- #235 
- 날짜 조회 css 수정
- API 수정
=> [Fix] 월세 및 관리비 페이지 css 수정

src/components/employees/Attendance.jsx, src/components/employees/AttendanceCheck.jsx, src/components/employees/LeaveWork.jsx, src/components/ui/HeaderToggle.jsx, src/pages/Home.jsx, src/styles/index.scss, src/styles/layout/headerToggleModal.scss, src/styles/page/employees/attendancecheck.scss, src/styles/page/home/homeAttendance.scss
- close #232 
- 메인 화면 출퇴근 버튼 CSS 수정
- 출퇴근 모달 CSS 수정
- 출퇴근 버튼 눈에 잘 안 보여서 논의 필요
=> [Add] 출퇴근 버튼 CSS

src/components/convenience/FindId.jsx, src/components/convenience/FindIdInfo.jsx, src/pages/Login.jsx, src/styles/page/convenience/findId.scss, src/styles/page/convenience/findIdInfo.scss, src/styles/page/convenience/login.scss
- #241 
- API 주소 수정
- catch 에러 메세지 추가
- page-title 추가
- css 수정
=> [Fix] 아이디 찾기 수정

src/components/convenience/ChangePw.jsx, src/components/convenience/FindPw.jsx, src/components/convenience/FindPwInfo.jsx, src/components/convenience/UpdateMyPage.jsx, src/styles/page/convenience/findPw.scss, src/styles/page/convenience/updateMyPage.scss
- #243 
- page-title 추가
- css 수정
- 비밀번호 찾기 유효성 검사 추가
- 휴대폰 번호 틀리게 입력하고 버튼 누르면 toast 에러 띄움
- 휴대폰 인증 틀리게 입력하고 버튼 누르면 toast 에러 띄움
- 정보 입력 없이 찾기 버튼 누르면 toast 에러 띄움
- 비밀번호 찾기에서 비밀번호 변경 유효성 검사
- page-title 추가
- 비밀번호 유효성 검사 통과 안된 상태에서 변경 버튼 누르면 toast 에러 띄움
- 정보 입력 없이 변경 버튼 누르면 toast 에러 띄움
=> [Fix] 비밀번호 찾기 수정

src/App.js, src/components/layout/Header.jsx, src/components/product/ProductNav.jsx, src/components/stock/StockNav.jsx, src/components/ui/HeaderMenu.jsx, src/components/ui/HeaderToggle.jsx, src/pages/ProductList.jsx, src/pages/ProductListTest.jsx, src/pages/ProductScroll.jsx, src/pages/Stock.jsx, src/styles/page/product.scss
- close #233 
- 상품페이지 무한스크롤 기능 구현
- IntersectionObserver 사용
- useState set이 느려서 nowPage 변수 선언해서 구현
- 추후 링크 수정 필요 (product, producttest)
=> [Add] 상품페이지 무한스크롤

src/components/employees/AddEmployeeModal.jsx, src/components/payment/Point.jsx, src/components/payment/RegisterPoint.jsx, src/components/ui/HeaderAlarm.jsx, src/pages/Payment.jsx, src/pages/Paymentlist.jsx, src/styles/page/payment/payment.scss, src/styles/page/payment/point.scss, src/styles/ui/numberPad.scss
=> [Add] 포인트 기능 구현 ver.1

src/App.js, src/pages/Login.jsx, src/pages/NotFound.jsx, src/styles/index.scss, src/styles/page/convenience/login.scss, src/styles/page/notFound.scss
- close #256
- 로그인 화면 CSS 수정
- 로고 추가
- 여백 수정
- 없는 페이지일 때 화면
- 존재하지 않는 페이지입니다 띄워줌
- 홈 버튼
=> [Add] 로그인 CSS 수정 + 에러페이지 추가

src/pages/Register.jsx, src/styles/page/convenience/register.scss
- #258 
- 비밀번호 특수문자 어떤걸 쓸 수 있는지 입력창에서 보여줄 수 있게 수정
- onBlur 함수 사용해서 지점명에 "점"을 입력 안하고 포커스가 이동되면 자동적으로 "점"을 추가해주도록 구현
- input css vw -> rem으로 수정 
- 주석 정리
- 비밀번호 input
=> [Fix] 회원가입 페이지 수정

src/components/analysis/DailySales.jsx, src/components/analysis/MonthlySales.jsx, src/components/analysis/YearSales.jsx, src/styles/page/analysis/sales.scss
- #267 
- 목록 버튼 만듬
- css 수정
- 날짜 선택 안하면 선택해달라는 toast 띄움
=> [Fix] 매출 분석 페이지 수정

package-lock.json, package.json, src/components/convenience/UpdateMyPage.jsx, src/components/home/HomeModal.jsx, src/components/order/OrderCartAddModal.jsx, src/components/order/OrderCartNav.jsx, src/components/order/OrderDetailNav.jsx, src/components/order/OrderListItem.jsx, src/components/stock/StockAddModal.jsx, src/components/stock/StockDispose.jsx, src/components/ui/HeaderAlarm.jsx, src/pages/Home.jsx, src/pages/Mypage.jsx, src/pages/Order.jsx, src/pages/OrderCart.jsx, src/pages/OrderDetail.jsx, src/pages/Payment.jsx, src/pages/ProductList.jsx, src/pages/ProductScroll.jsx, src/pages/Register.jsx, src/pages/Stock.jsx, src/styles/page/convenience/myPage.scss, src/styles/page/convenience/register.scss, src/styles/page/convenience/updateMyPage.scss, src/styles/page/notFound.scss, src/styles/page/payment/payment.scss, src/styles/page/product/product.scss
- close #270 
- redux 삭제
- convSeq 수정
- localStorage에서 가져오게 수정
- CSS 수정
- 마이페이지
- 마이페이지 수정
- 결제페이지
- 상품페이지 맨 위로 버튼 추가
- 알림 주석 처리된 거 수정
- 자잘한 단어 수정
- 발주 바구니 페이지 체크박스 에러 수정
=> [Fix] 전체적인 수정

src/components/analysis/AddCost.jsx, src/components/analysis/Calendar.jsx, src/components/analysis/Cost.jsx, src/components/analysis/UpdateCost.jsx, src/styles/page/analysis/addCost.scss, src/styles/page/analysis/cost.scss, src/styles/page/analysis/updateCost.scss
- #269 
- 전체적인 css 수정
- 월세 및 관리비 입력 페이지
- 기본값 0으로 설정
- 날짜 선택안하면 선택 요청하는 toast 추가
- 월세 및 관리비 수정 페이지
- 기본값 해당 월에 저장된 값으로 설정
- 날짜 선택안하면 선택 요청하는 toast 추가
- 조회하는 날짜 값 없으면 0원으로 표시
- Calendar costDate 속성 추가
- 캘린더 
- 현재 날짜를 받는 옵션 추가
=> [Add] 월세 및 관리비 페이지 수정

src/components/convenience/ChangePw.jsx, src/components/convenience/UpdateMyPage.jsx, src/pages/Login.jsx
- #274 
- 비밀번호 변경하면 로그아웃 처리, 로그인 페이지로 이동
=> [Fix] 회원정보 수정 페이지 수정

src/components/product/ProductItem.jsx, src/components/product/ProductNutrition.jsx, src/pages/Login.jsx, src/pages/ProductScroll.jsx, src/styles/page/convenience/login.scss, src/styles/page/product/productNutrition.scss
- close #280
- 상품 페이지 영양정보 모달에 상품명 영문 이름 추가
- 로그인 페이지 로고 크기 수정
- 태블릿에서 작아져서 크기 수정
=> [Add] 상품명 영문 이름 + 로고 크기 수정
